const data = {
products: [
    {
        _id : "1",
        title :"Over size T-shirt",
        content:"100% cutton printed high quality",
        keywords:" over size tshirt teshirt shirts printed basic asta",
        category:"shirts",
        brand: "adidas",
        rating: 4.5 ,
        numberOfRating: 2,
        price : 120,
        image : "/images/asta.png",
        inStoke : 10,
        colors : [{id:"1",color:"black"},{id:"2",color:"white"},{id:"3",color:"red"}],
        sizes : [{id:"1",size:"S"},{id:"2",size:"M"},{id:"3",size:"L"},{id:"4",size:"XL"},{id:"5",size:"2XL"}],
        sideImages : [{url:"/images/asta.png",id:"1"},{url:"/images/asta.png",id:"2"}]
    },{
        _id : "2",
        title :"nike shirts",
        keywords:" tshirt teshirt ",
        category:"pants",
        content:"comfortabl shirt",
        brand: "nike",
        rating: 1.5 ,
        numberOfRating: 5,
        price : 100,
        image : "/images/compass.png",
        inStoke : 2,
        colors : [{id:"1",color:"black"},{id:"2",color:"white"},{id:"3",color:"blue"}],
        sizes : [{id:"1",size:"S"},{id:"2",size:"M"},{id:"3",size:"L"},{id:"4",size:"XL"}],
        sideImages : [{url:"/imagescompass.png",id:"1"},{url:"/images/compass.png",id:"2"}]
    },{
         _id : "3",
        title :" t-shirt basic",
        keywords:" tshirt teshirt ",
        category:"shirts",
        content:"basic shirt",
        brand: "boma",
        rating: 5 ,
        numberOfRating: 8,
        price : 220,
        image : "/images/hunter.png",
        inStoke : 19,
        colors : [{id:"1",color:"black"},{id:"2",color:"white"},{id:"3",color:"green"}],
        sizes : [{id:"1",size:"M"},{id:"2",size:"L"},{id:"3",size:"XL"},{id:"4",size:"2XL"}],
        sideImages : [{url:"/images/hunter.png",id:"1"},{url:"/images/hunter.png",id:"2"},{url:"/images/hunter.png",id:"3"}]
    },{
         _id : "4",
        title :"Over size T-shirt",
        keywords:" tshirt teshirt ",
        category:"shirts",
        content:"great shirt",
        brand: "kalson",
        rating: 3 ,
        numberOfRating: 13,
        price : 210,
        image : "/images/hunter1.png",
        inStoke : 20,
        colors : [{id:"1",color:"black"},{id:"2",color:"white"}],
        sizes : [{id:"1",size:"S"},{id:"2",size:"M"},{id:"3",size:"L"}],
        sideImages : [{url:"/images/hunter1.png",id:"1"}]
    },{
         _id : "5",
        title :"Over size T-shirt",
        keywords:" tshirt teshirt ",
        category:"shirts",
        content:"great shirt",
        brand: "nothing",
        rating: 4 ,
        numberOfRating: 15,
        price : 150,
        image : "/images/killewa2.png",
        inStoke : 15,
        colors : [{id:"1",color:"black"},{id:"3",color:"red"}],
        sizes : [{id:"1",size:"S"},{id:"2",size:"M"}],
        sideImages : [{url:"/images/killewa2.png",id:"1"},{url:"/images/killewa2.png",id:"2"}]
    },{
        _id : "6",
        title :"Over size T-shirt",
        keywords:" tshirt teshirt ",
        category:"shirts",
        content:"great shirt",
        brand: "nothing",
        rating: 4 ,
        numberOfRating: 15,
        price : 150,
        image : "/images/moon.png",
        inStoke : 0,
        colors : [{id:"1",color:"black"}],
        sizes : [{id:"1",size:"M"}],
        sideImages : [{url:"/images/moon.png",id:"1"}]
    },{
        _id : "7",
        title :"Over size T-shirt",
        keywords:" tshirt teshirt ",
        category:"pants",
        content:"great shirt",
        brand: "nothing",
        rating: 4 ,
        numberOfRating: 15,
        price : 150,
        image : "/images/stayontouch.png",
        inStoke : 16,
        colors : [{id:"1",color:"black"},{id:"2",color:"white"},{id:"3",color:"yellow"}],
        sizes : [{id:"1",size:"S"},{id:"2",size:"M"},{id:"3",size:"L"},{id:"4",size:"XL"},{id:"5",size:"2XL"}],
        sideImages : [{url:"/images/stayontouch.png",id:"1"},{url:"/images/stayontouch.png",id:"2"},{url:"/images/mainpic.jpg",id:"3"},{url:"/images/mainpic.jpg",id:"4"}]
    },{
        _id : "8",
        title :"Over size T-shirt",
        keywords:" tshirt teshirt ",
        category:"shirts",
        content:"great shirt",
        brand: "nothing",
        rating: 4 ,
        numberOfRating: 15,
        price : 150,
        image : "/images/wave.png",
        inStoke : 5,
        colors : [{id:"1",color:"black"},{id:"2",color:"white"}],
        sizes : [{id:"1",size:"S"},{id:"2",size:"M"},{id:"3",size:"L"},{id:"4",size:"XL"},{id:"5",size:"2XL"}],
        sideImages : [{url:"/images/wave.png",id:"1"},{url:"/images/wave.png",id:"2"}]
    },{
         _id : "9",
        title :"Over size T-shirt",
        keywords:" tshirt teshirt ",
        category:"shirts",
        content:"great shirt",
        brand: "nike",
        rating: 1.5 ,
        numberOfRating: 5,
        price : 100,
        image : "/images/mainpic.jpg",
        inStoke : 2,
        colors : [{id:"1",color:"black"},{id:"2",color:"white"}],
        sizes : [{id:"1",size:"S"},{id:"2",size:"M"},{id:"3",size:"L"},{id:"4",size:"XL"},{id:"5",size:"2XL"}],
        sideImages : [{url:"/images/mainpic.jpg",id:"1"},{url:"/images/mainpic.jpg",id:"2"}]
    }
    
]

}
export default data;